AWSTemplateFormatVersion: 2010-09-09
Description: Creating an EC2 instance.
Resources:
  EC2Practise:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0bcf5425cdc1d8a85
      InstanceType: t2.micro
      KeyName: cfn-1
      SecurityGroups:
        - default
        - !Ref SSHSG
  SSHSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: This is SSH Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
  MyElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: !Ref EC2Practise